name: Check Conventional PR

on:
  pull_request:
    branches: [ 1.x ]

jobs:
  build:
    name: Ensure Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: beemojs/conventional-pr-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
